const PRODUCTS = [
  {
    "id": "box-digimon-1",
    "name": "Digimon - Caja 1",
    "type": "box",
    "category": "Digimon",
    "rarity": null,
    "price": 89.9,
    "stock": 5,
    "isNew": true,
    "img": "img/cajas/digimon_1.png",
    "description": "Caja sellada Digimon nº 1. Contenido oficial.",
    "bestseller": true,
    "language": "Spanish"
  },
  {
    "id": "box-digimon-2",
    "name": "Digimon - Caja 2",
    "type": "box",
    "category": "Digimon",
    "rarity": null,
    "price": 94.9,
    "stock": 5,
    "isNew": false,
    "img": "img/cajas/digimon_2.png",
    "description": "Caja sellada Digimon nº 2. Contenido oficial.",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "box-digimon-3",
    "name": "Digimon - Caja 3",
    "type": "box",
    "category": "Digimon",
    "rarity": null,
    "price": 99.9,
    "stock": 5,
    "isNew": false,
    "img": "img/cajas/digimon_3.png",
    "description": "Caja sellada Digimon nº 3. Contenido oficial.",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "box-digimon-4",
    "name": "Digimon - Caja 4",
    "type": "box",
    "category": "Digimon",
    "rarity": null,
    "price": 104.9,
    "stock": 0,
    "isNew": false,
    "img": "img/cajas/digimon_4.png",
    "description": "Caja sellada Digimon nº 4. Contenido oficial.",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "box-dragonball-1",
    "name": "Dragonball - Caja 1",
    "type": "box",
    "category": "Dragonball",
    "rarity": null,
    "price": 94.5,
    "stock": 5,
    "isNew": true,
    "img": "img/cajas/dragonball_1.png",
    "description": "Caja sellada Dragonball nº 1. Contenido oficial.",
    "bestseller": true,
    "language": "Spanish"
  },
  {
    "id": "box-dragonball-2",
    "name": "Dragonball - Caja 2",
    "type": "box",
    "category": "Dragonball",
    "rarity": null,
    "price": 99.5,
    "stock": 5,
    "isNew": false,
    "img": "img/cajas/dragonball_2.png",
    "description": "Caja sellada Dragonball nº 2. Contenido oficial.",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "box-dragonball-3",
    "name": "Dragonball - Caja 3",
    "type": "box",
    "category": "Dragonball",
    "rarity": null,
    "price": 104.5,
    "stock": 5,
    "isNew": false,
    "img": "img/cajas/dragonball_3.png",
    "description": "Caja sellada Dragonball nº 3. Contenido oficial.",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "box-dragonball-4",
    "name": "Dragonball - Caja 4",
    "type": "box",
    "category": "Dragonball",
    "rarity": null,
    "price": 109.5,
    "stock": 0,
    "isNew": false,
    "img": "img/cajas/dragonball_4.png",
    "description": "Caja sellada Dragonball nº 4. Contenido oficial.",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "box-magic-1",
    "name": "Magic - Caja 1",
    "type": "box",
    "category": "Magic",
    "rarity": null,
    "price": 119.9,
    "stock": 5,
    "isNew": true,
    "img": "img/cajas/magic_1.png",
    "description": "Caja sellada Magic nº 1. Contenido oficial.",
    "bestseller": true,
    "language": "Spanish"
  },
  {
    "id": "box-magic-2",
    "name": "Magic - Caja 2",
    "type": "box",
    "category": "Magic",
    "rarity": null,
    "price": 124.9,
    "stock": 5,
    "isNew": false,
    "img": "img/cajas/magic_2.png",
    "description": "Caja sellada Magic nº 2. Contenido oficial.",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "box-magic-3",
    "name": "Magic - Caja 3",
    "type": "box",
    "category": "Magic",
    "rarity": null,
    "price": 129.9,
    "stock": 5,
    "isNew": false,
    "img": "img/cajas/magic_3.png",
    "description": "Caja sellada Magic nº 3. Contenido oficial.",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "box-magic-4",
    "name": "Magic - Caja 4",
    "type": "box",
    "category": "Magic",
    "rarity": null,
    "price": 134.9,
    "stock": 0,
    "isNew": false,
    "img": "img/cajas/magic_4.png",
    "description": "Caja sellada Magic nº 4. Contenido oficial.",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "box-one_piece-1",
    "name": "One Piece - Caja 1",
    "type": "box",
    "category": "One Piece",
    "rarity": null,
    "price": 129.99,
    "stock": 5,
    "isNew": true,
    "img": "img/cajas/one_piece_1.png",
    "description": "Caja sellada One Piece nº 1. Contenido oficial.",
    "bestseller": true,
    "language": "Spanish"
  },
  {
    "id": "box-one_piece-2",
    "name": "One Piece - Caja 2",
    "type": "box",
    "category": "One Piece",
    "rarity": null,
    "price": 134.99,
    "stock": 5,
    "isNew": false,
    "img": "img/cajas/one_piece_2.png",
    "description": "Caja sellada One Piece nº 2. Contenido oficial.",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "box-one_piece-3",
    "name": "One Piece - Caja 3",
    "type": "box",
    "category": "One Piece",
    "rarity": null,
    "price": 139.99,
    "stock": 5,
    "isNew": false,
    "img": "img/cajas/one_piece_3.png",
    "description": "Caja sellada One Piece nº 3. Contenido oficial.",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "box-one_piece-4",
    "name": "One Piece - Caja 4",
    "type": "box",
    "category": "One Piece",
    "rarity": null,
    "price": 144.99,
    "stock": 0,
    "isNew": false,
    "img": "img/cajas/one_piece_4.png",
    "description": "Caja sellada One Piece nº 4. Contenido oficial.",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "box-one_piece-5",
    "name": "One Piece - Caja 5",
    "type": "box",
    "category": "One Piece",
    "rarity": null,
    "price": 149.99,
    "stock": 5,
    "isNew": false,
    "img": "img/cajas/one_piece_5.png",
    "description": "Caja sellada One Piece nº 5. Contenido oficial.",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "box-one_piece-1",
    "name": "One_Piece - Caja 1",
    "type": "box",
    "category": "One Piece",
    "rarity": null,
    "price": 129.99,
    "stock": 5,
    "isNew": true,
    "img": "img/cajas/one_piece_1.png",
    "description": "Caja sellada One_Piece nº 1. Contenido oficial.",
    "bestseller": true,
    "language": "Spanish"
  },
  {
    "id": "box-one_piece-2",
    "name": "One_Piece - Caja 2",
    "type": "box",
    "category": "One Piece",
    "rarity": null,
    "price": 134.99,
    "stock": 5,
    "isNew": false,
    "img": "img/cajas/one_piece_2.png",
    "description": "Caja sellada One_Piece nº 2. Contenido oficial.",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "box-one_piece-3",
    "name": "One_Piece - Caja 3",
    "type": "box",
    "category": "One Piece",
    "rarity": null,
    "price": 139.99,
    "stock": 5,
    "isNew": false,
    "img": "img/cajas/one_piece_3.png",
    "description": "Caja sellada One_Piece nº 3. Contenido oficial.",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "box-pokemon-1",
    "name": "Pokemon - Caja 1",
    "type": "box",
    "category": "Pokemon",
    "rarity": null,
    "price": 159.9,
    "stock": 5,
    "isNew": true,
    "img": "img/cajas/pokemon_1.png",
    "description": "Caja sellada Pokemon nº 1. Contenido oficial.",
    "bestseller": true,
    "language": "Spanish"
  },
  {
    "id": "box-pokemon-2",
    "name": "Pokemon - Caja 2",
    "type": "box",
    "category": "Pokemon",
    "rarity": null,
    "price": 164.9,
    "stock": 5,
    "isNew": false,
    "img": "img/cajas/pokemon_2.png",
    "description": "Caja sellada Pokemon nº 2. Contenido oficial.",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "box-pokemon-3",
    "name": "Pokemon - Caja 3",
    "type": "box",
    "category": "Pokemon",
    "rarity": null,
    "price": 169.9,
    "stock": 5,
    "isNew": false,
    "img": "img/cajas/pokemon_3.png",
    "description": "Caja sellada Pokemon nº 3. Contenido oficial.",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "box-pokemon-4",
    "name": "Pokemon - Caja 4",
    "type": "box",
    "category": "Pokemon",
    "rarity": null,
    "price": 174.9,
    "stock": 0,
    "isNew": false,
    "img": "img/cajas/pokemon_4.png",
    "description": "Caja sellada Pokemon nº 4. Contenido oficial.",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "box-yugioh-1",
    "name": "Yugioh - Caja 1",
    "type": "box",
    "category": "Yugioh",
    "rarity": null,
    "price": 79.9,
    "stock": 5,
    "isNew": true,
    "img": "img/cajas/yugioh_1.png",
    "description": "Caja sellada Yugioh nº 1. Contenido oficial.",
    "bestseller": true,
    "language": "Spanish"
  },
  {
    "id": "box-yugioh-2",
    "name": "Yugioh - Caja 2",
    "type": "box",
    "category": "Yugioh",
    "rarity": null,
    "price": 84.9,
    "stock": 5,
    "isNew": false,
    "img": "img/cajas/yugioh_2.png",
    "description": "Caja sellada Yugioh nº 2. Contenido oficial.",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "box-yugioh-3",
    "name": "Yugioh - Caja 3",
    "type": "box",
    "category": "Yugioh",
    "rarity": null,
    "price": 89.9,
    "stock": 5,
    "isNew": false,
    "img": "img/cajas/yugioh_3.png",
    "description": "Caja sellada Yugioh nº 3. Contenido oficial.",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "box-yugioh-4",
    "name": "Yugioh - Caja 4",
    "type": "box",
    "category": "Yugioh",
    "rarity": null,
    "price": 94.9,
    "stock": 0,
    "isNew": false,
    "img": "img/cajas/yugioh_4.png",
    "description": "Caja sellada Yugioh nº 4. Contenido oficial.",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "card-digimon-1",
    "name": "Digimon Card 1",
    "type": "card",
    "category": "Digimon",
    "rarity": "Secret Rare",
    "price": 24.99,
    "stock": 10,
    "isNew": true,
    "img": "img/cartas/digimon_1.png",
    "description": "Carta suelta Digimon #1. Estado Near Mint (demo).",
    "bestseller": true,
    "language": "Spanish"
  },
  {
    "id": "card-digimon-2",
    "name": "Digimon Card 2",
    "type": "card",
    "category": "Digimon",
    "rarity": "UR",
    "price": 26.99,
    "stock": 10,
    "isNew": false,
    "img": "img/cartas/digimon_2.png",
    "description": "Carta suelta Digimon #2. Estado Near Mint (demo).",
    "bestseller": true,
    "language": "Spanish"
  },
  {
    "id": "card-digimon-3",
    "name": "Digimon Card 3",
    "type": "card",
    "category": "Digimon",
    "rarity": null,
    "price": 28.99,
    "stock": 0,
    "isNew": false,
    "img": "img/cartas/digimon_3.jpg",
    "description": "Carta suelta Digimon #3. Estado Near Mint (demo).",
    "bestseller": false,
    "language": "Japanese"
  },
  {
    "id": "card-digimon-4",
    "name": "Digimon Card 4",
    "type": "card",
    "category": "Digimon",
    "rarity": null,
    "price": 30.99,
    "stock": 10,
    "isNew": false,
    "img": "img/cartas/digimon_4.png",
    "description": "Carta suelta Digimon #4. Estado Near Mint (demo).",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "card-onepiece-1",
    "name": "Onepiece Card 1",
    "type": "card",
    "category": "Onepiece",
    "rarity": "Secret Rare",
    "price": 79.99,
    "stock": 10,
    "isNew": true,
    "img": "img/cartas/onepiece_1.png",
    "description": "Carta suelta Onepiece #1. Estado Near Mint (demo).",
    "bestseller": true,
    "language": "Spanish"
  },
  {
    "id": "card-onepiece-2",
    "name": "Onepiece Card 2",
    "type": "card",
    "category": "Onepiece",
    "rarity": "UR",
    "price": 81.99,
    "stock": 10,
    "isNew": false,
    "img": "img/cartas/onepiece_2.jpg",
    "description": "Carta suelta Onepiece #2. Estado Near Mint (demo).",
    "bestseller": true,
    "language": "Japanese"
  },
  {
    "id": "card-onepiece-3",
    "name": "Onepiece Card 3",
    "type": "card",
    "category": "Onepiece",
    "rarity": null,
    "price": 83.99,
    "stock": 0,
    "isNew": false,
    "img": "img/cartas/onepiece_3.png",
    "description": "Carta suelta Onepiece #3. Estado Near Mint (demo).",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "card-onepiece-4",
    "name": "Onepiece Card 4",
    "type": "card",
    "category": "Onepiece",
    "rarity": null,
    "price": 85.99,
    "stock": 10,
    "isNew": false,
    "img": "img/cartas/onepiece_4.jpg",
    "description": "Carta suelta Onepiece #4. Estado Near Mint (demo).",
    "bestseller": false,
    "language": "Japanese"
  },
  {
    "id": "card-onepiece-5",
    "name": "Onepiece Card 5",
    "type": "card",
    "category": "Onepiece",
    "rarity": null,
    "price": 87.99,
    "stock": 10,
    "isNew": false,
    "img": "img/cartas/onepiece_5.png",
    "description": "Carta suelta Onepiece #5. Estado Near Mint (demo).",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "card-pokemon-1",
    "name": "Pokemon Card 1",
    "type": "card",
    "category": "Pokemon",
    "rarity": "Secret Rare",
    "price": 39.0,
    "stock": 10,
    "isNew": true,
    "img": "img/cartas/pokemon_1.png",
    "description": "Carta suelta Pokemon #1. Estado Near Mint (demo).",
    "bestseller": true,
    "language": "Spanish"
  },
  {
    "id": "card-pokemon-2",
    "name": "Pokemon Card 2",
    "type": "card",
    "category": "Pokemon",
    "rarity": "UR",
    "price": 41.0,
    "stock": 10,
    "isNew": false,
    "img": "img/cartas/pokemon_2.png",
    "description": "Carta suelta Pokemon #2. Estado Near Mint (demo).",
    "bestseller": true,
    "language": "Spanish"
  },
  {
    "id": "card-pokemon-3",
    "name": "Pokemon Card 3",
    "type": "card",
    "category": "Pokemon",
    "rarity": null,
    "price": 43.0,
    "stock": 0,
    "isNew": false,
    "img": "img/cartas/pokemon_3.jpg",
    "description": "Carta suelta Pokemon #3. Estado Near Mint (demo).",
    "bestseller": false,
    "language": "Japanese"
  },
  {
    "id": "card-pokemon-4",
    "name": "Pokemon Card 4",
    "type": "card",
    "category": "Pokemon",
    "rarity": null,
    "price": 45.0,
    "stock": 10,
    "isNew": false,
    "img": "img/cartas/pokemon_4.png",
    "description": "Carta suelta Pokemon #4. Estado Near Mint (demo).",
    "bestseller": false,
    "language": "Spanish"
  },
  {
    "id": "card-pokemon-5",
    "name": "Pokemon Card 5",
    "type": "card",
    "category": "Pokemon",
    "rarity": null,
    "price": 47.0,
    "stock": 10,
    "isNew": false,
    "img": "img/cartas/pokemon_5.jpg",
    "description": "Carta suelta Pokemon #5. Estado Near Mint (demo).",
    "bestseller": false,
    "language": "Japanese"
  },
  {
    "id": "oth-album",
    "name": "Álbum para cartas",
    "type": "other",
    "category": "Otros",
    "kind": "Albums",
    "rarity": null,
    "price": 19.99,
    "stock": 10,
    "isNew": true,
    "img": "img/otros/album.png",
    "description": "Albums para TCG.",
    "bestseller": false,
    "language": "Universal"
  },
  {
    "id": "oth-deckbox1",
    "name": "Deck Box",
    "type": "other",
    "category": "Otros",
    "kind": "Deck Boxes",
    "rarity": null,
    "price": 9.99,
    "stock": 10,
    "isNew": true,
    "img": "img/otros/deckbox1.webp",
    "description": "Deck Boxes para TCG.",
    "bestseller": false,
    "language": "Universal"
  },
  {
    "id": "oth-deckbox2",
    "name": "Deck Box",
    "type": "other",
    "category": "Otros",
    "kind": "Deck Boxes",
    "rarity": null,
    "price": 9.99,
    "stock": 10,
    "isNew": true,
    "img": "img/otros/deckbox2.jpg",
    "description": "Deck Boxes para TCG.",
    "bestseller": false,
    "language": "Universal"
  },
  {
    "id": "oth-funda",
    "name": "Fundas (Sleeves) — 100u",
    "type": "other",
    "category": "Otros",
    "kind": "Sleeves",
    "rarity": null,
    "price": 12.99,
    "stock": 10,
    "isNew": true,
    "img": "img/otros/funda.webp",
    "description": "Sleeves para TCG.",
    "bestseller": true,
    "language": "Universal"
  },
  {
    "id": "oth-tapete",
    "name": "Playmat",
    "type": "other",
    "category": "Otros",
    "kind": "Playmats",
    "rarity": null,
    "price": 24.99,
    "stock": 10,
    "isNew": true,
    "img": "img/otros/tapete.webp",
    "description": "Playmats para TCG.",
    "bestseller": true,
    "language": "Universal"
  }
];

const CATEGORIES = [
  "Pokemon",
  "One Piece",
  "Naruto",
  "Dragon Ball",
  "Magic",
  "Digimon",
  "Spiderman",
  "Metazco",
  "Otros"
];
const LANGUAGES = [
  "English",
  "Spanish",
  "Japanese",
  "Universal"
];
const OTHER_KINDS = [
  "Sleeves",
  "Albums",
  "Deck Boxes",
  "Playmats",
  "Others"
];
