const PRODUCTS = [
  {
    id: "box-op-01",
    name: "One Piece TCG - Romance Dawn Booster Box",
    type: "box",
    category: "One Piece",
    rarity: null,
    price: 129.99,
    stock: 5,
    isNew: false,
    img: "img/cajas/op_romance.jpg",
    description: "Caja sellada OP-01. 24 sobres. Idioma: Español.",
    bestseller: true,
  },
  {
    id: "box-pkmn-151",
    name: "Pokémon - Scarlet & Violet 151 Display",
    type: "box",
    category: "Pokemon",
    rarity: null,
    price: 159.90,
    stock: 2,
    isNew: true,
    img: "img/cajas/pokemon_151.jpg",
    description: "Display edición 151. Sellada. Español.",
    bestseller: true,
  },
  {
    id: "box-dbmz-hero",
    name: "Dragon Ball Super - Fighter's History Box",
    type: "box",
    category: "Dragon Ball",
    rarity: null,
    price: 94.50,
    stock: 0,
    isNew: false,
    img: "img/cajas/db_fighters.jpg",
    description: "Caja booster DBS. 24 sobres.",
    bestseller: false,
  },

  {
    id: "card-pika-alt",
    name: "Pikachu Illustration Rare",
    type: "card",
    category: "Pokemon",
    rarity: "Illustration Rare",
    price: 39.00,
    stock: 10,
    isNew: false,
    img: "img/cartas/pikachu_alt.jpg",
    description: "Carta coleccionista. Near Mint.",
    bestseller: true,
  },
  {
    id: "card-luffy-sec",
    name: "Monkey D. Luffy (Secret Rare)",
    type: "card",
    category: "One Piece",
    rarity: "Secret Rare",
    price: 79.99,
    stock: 1,
    isNew: true,
    img: "img/cartas/luffy_secret.jpg",
    description: "OP TCG Secret Rare. JP print.",
    bestseller: true,
  },
  {
    id: "card-goku-ur",
    name: "SSB Goku Ultra Rare",
    type: "card",
    category: "Dragon Ball",
    rarity: "UR",
    price: 24.99,
    stock: 0,
    isNew: false,
    img: "img/cartas/goku_ur.jpg",
    description: "Dragon Ball Super TCG. Español.",
    bestseller: false,
  },

  {
    id: "oth-sleeves-matte",
    name: "Fundas Matte Dragon Shield (100u)",
    type: "other",
    category: "Otros",
    rarity: null,
    price: 12.99,
    stock: 20,
    isNew: false,
    img: "img/otros/sleeves_matte.jpg",
    description: "Fundas tamaño estándar. Anti-glare.",
    bestseller: true,
  },
  {
    id: "oth-playmat-zoro",
    name: "Playmat One Piece - Zoro",
    type: "other",
    category: "One Piece",
    rarity: null,
    price: 24.99,
    stock: 4,
    isNew: true,
    img: "img/otros/playmat_zoro.jpg",
    description: "Tapete de juego 60x35cm.",
    bestseller: false,
  },
];

const CATEGORIES = [
  "Pokemon",
  "One Piece",
  "Naruto",
  "Dragon Ball",
  "Magic",
  "Digimon",
  "Spiderman",
  "Metazco",
  "Otros"
];
